// Database-related types

import type { Row } from './entities.js';

export type DatabaseType = 'sqlite' | 'postgres';

// Database type constants (matching Electron format)
export interface DatabaseTypeRef {
  id: number;
  name: string;
  type: DatabaseType;
}

export const DATABASE_TYPE_SQLITE: DatabaseTypeRef = { id: 0, name: 'SQLite', type: 'sqlite' };
export const DATABASE_TYPE_POSTGRES: DatabaseTypeRef = { id: 1, name: 'PostgreSQL', type: 'postgres' };
export const DATABASE_TYPES: DatabaseTypeRef[] = [DATABASE_TYPE_SQLITE, DATABASE_TYPE_POSTGRES];

export interface DatabaseConfig {
  type: DatabaseType;
  // SQLite
  filepath?: string;
  // PostgreSQL
  host?: string;
  port?: number;
  database?: string;
  user?: string;
  password?: string;
}

export interface QueryResult<T = unknown> {
  rows: T[];
  rowCount: number;
}

/**
 * Result from INSERT/UPDATE/DELETE operations.
 * Enhanced from Electron's pattern to include RETURNING clause results.
 */
export interface DbResult {
  /** Last inserted row ID (only populated if a numeric 'id' column was returned) */
  lastID?: number;
  changes: number;
  /** Rows returned from RETURNING * clause (empty array for operations without RETURNING) */
  rows: Row[];
}

export interface DatabaseConnection {
  id: string;
  config: DatabaseConfig;
  connected: boolean;
}

/**
 * Transaction context for database operations.
 * Represents an active transaction connection that can be passed to CRUD operations.
 */
export interface TransactionContext {
  id: string;
}

// Database operation types
export const DB_OP_CREATE = 0;
export const DB_OP_DELETE = 1;
export const DB_OP_UPDATE = 2;
export const DB_OP_ALTER = 3;
export type DbOpType =
  | typeof DB_OP_CREATE
  | typeof DB_OP_DELETE
  | typeof DB_OP_UPDATE
  | typeof DB_OP_ALTER;

/**
 * Notification metadata for database operations.
 * Simplified structure - backend uses RETURNING * to get affected rows automatically.
 */
export interface DbNotificationMeta {
  table: string;
  operation: 'insert' | 'update' | 'delete' | 'alter';
  // Backend appends RETURNING * to DML operations and gets affected rows from query result
  // No need to pass row data - database tells us what changed
}

/**
 * Batch operation for executing multiple statements in a transaction.
 * All statements are executed and then IDs are returned.
 * Use this when you don't need to reference INSERT IDs within the same batch.
 */
export interface DbBatchStatement {
  sql: string;
  params?: unknown[];
  /** Optional notification metadata (auto-generated by CRUD methods) */
  notificationMeta?: DbNotificationMeta;
}

/**
 * Transaction statement for executing within a managed transaction.
 * Statements are executed sequentially and can reference results from previous statements.
 * Use this when you need to reference INSERT IDs in subsequent statements within the same transaction.
 */
export interface DbTransactionStatement {
  sql: string;
  params?: unknown[];
  /** Optional notification metadata (auto-generated by CRUD methods) */
  notificationMeta?: DbNotificationMeta;
}

/**
 * Transaction function type.
 * Receives a connection to execute operations within a transaction.
 * Matches Electron's DbTransaction pattern.
 */
export type DbTransaction = (connection: TransactionContext) => Promise<void>;
