/**
 * Message types for communication between UI webview and extension backend.
 * Used by both the UI package and IDE plugin packages (VSCode, Rider, etc.)
 */

import type { DatabaseType, DatabaseConfig, DbNotificationMeta, DbBatchStatement, TransactionContext } from './database.js';

// Re-export for convenience
export type { DbNotificationMeta, DbBatchStatement };

// ============================================================================
// Messages FROM UI TO Extension
// ============================================================================

export interface ReadyMessage {
	type: 'ready';
}

export interface DbQueryMessage {
	type: 'db:query';
	id: string;
	sql: string;
	params?: unknown[];
	/** Optional transaction context */
	context?: TransactionContext;
}

/**
 * Execute DDL statements (CREATE, ALTER, DROP).
 * No parameters supported - for DML with params, use DbRunMessage.
 */
export interface DbExecMessage {
	type: 'db:exec';
	id: string;
	sql: string;
	/** Optional notification metadata (auto-generated by CRUD methods) */
	notificationMeta?: DbNotificationMeta;
	/** Optional transaction context */
	context?: TransactionContext;
}

/**
 * Execute DML statements (INSERT, UPDATE, DELETE).
 */
export interface DbRunMessage {
	type: 'db:run';
	id: string;
	sql: string;
	params?: unknown[];
	/** If true, expects SQL to have RETURNING clause and will return rows */
	returning?: boolean;
	/** Optional notification metadata (auto-generated by CRUD methods) */
	notificationMeta?: DbNotificationMeta;
	/** Optional transaction context */
	context?: TransactionContext;
}

export interface DbConnectMessage {
	type: 'db:connect';
	config: DatabaseConfig;
	/** If true, create a new database (initialize schema) */
	createNew?: boolean;
}

export interface DbDisconnectMessage {
	type: 'db:disconnect';
}

export interface DialogOpenSqliteMessage {
	type: 'dialog:openSqlite';
	id: string;
}

export interface DialogSaveSqliteMessage {
	type: 'dialog:saveSqlite';
	id: string;
}

export interface DialogOpenCsvMessage {
	type: 'dialog:openCsv';
	id: string;
}

export interface DialogSaveCsvMessage {
	type: 'dialog:saveCsv';
	id: string;
	defaultFilename?: string;
}

export interface DialogSelectFolderMessage {
	type: 'dialog:selectFolder';
	id: string;
	title?: string;
}

export interface FileReadMessage {
	type: 'file:read';
	id: string;
	filePath: string;
}

export interface FileWriteMessage {
	type: 'file:write';
	id: string;
	filePath: string;
	content: string;
}

export interface FileCreateMessage {
	type: 'file:create';
	id: string;
	filePath: string;
}

export interface FileAppendMessage {
	type: 'file:append';
	id: string;
	filePath: string;
	content: string;
}

export interface FileMakeDirMessage {
	type: 'file:mkdir';
	id: string;
	dirPath: string;
}

export interface FileWriteBinaryMessage {
	type: 'file:writeBinary';
	id: string;
	filePath: string;
	/** Binary content as base64-encoded string */
	contentBase64: string;
}

export interface FileRenameMessage {
	type: 'file:rename';
	id: string;
	oldPath: string;
	newPath: string;
}

export interface FileExistsMessage {
	type: 'file:exists';
	id: string;
	filePath: string;
}

export interface ScannerScanMessage {
	type: 'scanner:scan';
}

export interface EditorOpenFileMessage {
	type: 'editor:openFile';
	filePath: string;
	lineNumber?: number;
}

export interface EditorCreateFileMessage {
	type: 'editor:createFile';
	filePath: string;
	content: string;
}

/**
 * Request to get a method body from a conversation code file.
 * Uses IDE symbol provider to find the method.
 */
export interface CodeGetMethodMessage {
	type: 'code:getMethod';
	id: string;
	conversationId: number;
	methodName: string; // e.g., "Node_123_Condition"
	/** File extension including the dot (e.g., '.cs', '.cpp') */
	fileExtension: string;
}

/**
 * Code template types for different game engines.
 */
export type CodeTemplateType = 'unity' | 'godot' | 'unreal';

/**
 * Request to create a method stub and open it in the IDE.
 * The UI generates the code; the IDE plugin just writes it.
 */
export interface CodeCreateMethodMessage {
	type: 'code:createMethod';
	id: string;
	conversationId: number;
	methodName: string;
	/** File extension including the dot (e.g., '.cs', '.cpp') */
	fileExtension: string;
	/** Generated method stub code */
	methodStub: string;
	/** Generated file content (used when creating a new file) */
	fileContent: string;
}

/**
 * Request to delete a method with diff preview (interactive).
 * Returns whether the user accepted or rejected the deletion.
 */
export interface CodeDeleteMethodMessage {
	type: 'code:deleteMethod';
	id: string;
	conversationId: number;
	methodName: string;
	/** File extension including the dot (e.g., '.cs', '.cpp') */
	fileExtension: string;
}

/**
 * Request to delete multiple methods without confirmation (programmatic).
 * Used when deleting nodes - returns the deleted code for each method for undo.
 * Methods are deleted in a single file operation to avoid stale symbol issues.
 */
export interface CodeDeleteMethodsSilentMessage {
	type: 'code:deleteMethodsSilent';
	id: string;
	conversationId: number;
	methodNames: string[];
	/** File extension including the dot (e.g., '.cs', '.cpp') */
	fileExtension: string;
}

/**
 * Request to restore a previously deleted method.
 * Used for undo after node deletion.
 */
export interface CodeRestoreMethodMessage {
	type: 'code:restoreMethod';
	id: string;
	conversationId: number;
	methodName: string;
	/** The method code to restore (includes attribute and body) */
	code: string;
	/** File extension including the dot (e.g., '.cs', '.cpp') */
	fileExtension: string;
	/** Generated file content (used when recreating a deleted file) */
	fileContent: string;
}

/**
 * Request to delete an entire conversation code file.
 * Used when permanently deleting a conversation.
 */
export interface CodeDeleteFileMessage {
	type: 'code:deleteFile';
	id: string;
	conversationId: number;
	/** File extension including the dot (e.g., '.cs', '.cpp') */
	fileExtension: string;
}

/**
 * Request to restore an entire conversation code file.
 * Used for undo after conversation deletion.
 */
export interface CodeRestoreFileMessage {
	type: 'code:restoreFile';
	id: string;
	conversationId: number;
	content: string;
	/** File extension including the dot (e.g., '.cs', '.cpp') */
	fileExtension: string;
}

/**
 * Request to open a method in the IDE (go to symbol).
 */
export interface CodeOpenMethodMessage {
	type: 'code:openMethod';
	conversationId: number;
	methodName: string;
	/** File extension including the dot (e.g., '.cs', '.cpp') */
	fileExtension: string;
}

/**
 * Request to set up file watcher for code files.
 * Sent by UI when code output folder is known/changes.
 * Pass null/undefined to clear the watcher.
 */
export interface CodeWatchFolderMessage {
	type: 'code:watchFolder';
	/** Relative path to the code output folder, or null to clear */
	folderPath: string | null;
}

/**
 * Request to set up file watcher for the snapshot output folder.
 * Watches for command.tmp files written by game engine plugins (Unity, Godot).
 * Pass null to clear the watcher.
 */
export interface SnapshotWatchFolderMessage {
	type: 'snapshot:watchFolder';
	/** Relative path to the snapshot output folder, or null to clear */
	folderPath: string | null;
}

export type NotificationLevel = 'info' | 'warning' | 'error';

export interface NotifyMessage {
	type: 'notify';
	level: NotificationLevel;
	message: string;
	detail?: string;
}

export interface StatusMessage {
	type: 'status';
	message: string;
	timeoutMs?: number;
}

/**
 * Focus/selection types for cross-panel synchronization.
 */
// Plural forms used by internal focus system
export type FocusableTablePlural = 'conversations' | 'nodes' | 'edges' | 'actors' | 'locales' | 'localizations';
// Singular forms used by game engine IPC commands
export type FocusableTableSingular = 'conversation' | 'actor' | 'locale' | 'localization';
// Combined type for all focusable tables
export type FocusableTable = FocusableTablePlural | FocusableTableSingular;

export interface FocusItem {
	id: number;
	payload?: Record<string, unknown>;
}

export interface FocusSetMessage {
	type: 'focus:set';
	table: FocusableTable;
	items: FocusItem[];
}

export interface DbBatchMessage {
	type: 'db:batch';
	id: string;
	statements: DbBatchStatement[];
}

export interface DbTransactionBeginMessage {
	type: 'db:transaction:begin';
	id: string;
}

export interface DbTransactionCommitMessage {
	type: 'db:transaction:commit';
	id: string;
	/** Transaction context returned from begin */
	context: TransactionContext;
}

export interface DbTransactionRollbackMessage {
	type: 'db:transaction:rollback';
	id: string;
	/** Transaction context returned from begin */
	context: TransactionContext;
}

/**
 * Union type of all messages sent FROM UI TO Extension
 */
export type OutgoingMessage =
	| ReadyMessage
	| DbQueryMessage
	| DbExecMessage
	| DbRunMessage
	| DbBatchMessage
	| DbTransactionBeginMessage
	| DbTransactionCommitMessage
	| DbTransactionRollbackMessage
	| DbConnectMessage
	| DbDisconnectMessage
	| DialogOpenSqliteMessage
	| DialogSaveSqliteMessage
	| DialogOpenCsvMessage
	| DialogSaveCsvMessage
	| DialogSelectFolderMessage
	| FileReadMessage
	| FileWriteMessage
	| FileCreateMessage
	| FileAppendMessage
	| FileMakeDirMessage
	| FileWriteBinaryMessage
	| FileRenameMessage
	| FileExistsMessage
	| ScannerScanMessage
	| EditorOpenFileMessage
	| EditorCreateFileMessage
	| NotifyMessage
	| StatusMessage
	| FocusSetMessage
	| CodeGetMethodMessage
	| CodeCreateMethodMessage
	| CodeDeleteMethodMessage
	| CodeDeleteMethodsSilentMessage
	| CodeRestoreMethodMessage
	| CodeDeleteFileMessage
	| CodeRestoreFileMessage
	| CodeOpenMethodMessage
	| CodeWatchFolderMessage
	| SnapshotWatchFolderMessage;

// ============================================================================
// Messages FROM Extension TO UI
// ============================================================================

export interface ConnectedMessage {
	type: 'connected';
	dbType: DatabaseType;
}

export interface DisconnectedMessage {
	type: 'disconnected';
	dbType: DatabaseType | null;
}

export interface DbQueryResultMessage {
	type: 'db:queryResult';
	id: string;
	success: true;
	data: unknown[];
}

export interface DbQueryErrorMessage {
	type: 'db:queryResult';
	id: string;
	success: false;
	error: string;
}

export interface DbExecResultMessage {
	type: 'db:execResult';
	id: string;
	success: true;
}

export interface DbExecErrorMessage {
	type: 'db:execResult';
	id: string;
	success: false;
	error: string;
}

export interface DbRunResultMessage {
	type: 'db:runResult';
	id: string;
	success: true;
	/** Last inserted row ID (only populated if a numeric 'id' column was returned) */
	lastID?: number;
	changes: number;
	/** Rows returned from RETURNING clause */
	rows: unknown[];
}

export interface DbRunErrorMessage {
	type: 'db:runResult';
	id: string;
	success: false;
	error: string;
}

export interface DbBatchResultMessage {
	type: 'db:batchResult';
	id: string;
	success: true;
	/** Last inserted IDs for INSERT statements */
	insertIds?: number[];
}

export interface DbBatchErrorMessage {
	type: 'db:batchResult';
	id: string;
	success: false;
	error: string;
}

export interface DbTransactionBeginResultMessage {
	type: 'db:transactionBeginResult';
	id: string;
	success: true;
	context: TransactionContext;
}

export interface DbTransactionBeginErrorMessage {
	type: 'db:transactionBeginResult';
	id: string;
	success: false;
	error: string;
}

export interface DbTransactionCommitResultMessage {
	type: 'db:transactionCommitResult';
	id: string;
	success: true;
}

export interface DbTransactionCommitErrorMessage {
	type: 'db:transactionCommitResult';
	id: string;
	success: false;
	error: string;
}

export interface DbTransactionRollbackResultMessage {
	type: 'db:transactionRollbackResult';
	id: string;
	success: true;
}

export interface DbTransactionRollbackErrorMessage {
	type: 'db:transactionRollbackResult';
	id: string;
	success: false;
	error: string;
}

export type ChangeOperation = 'insert' | 'update' | 'delete' | 'alter';

export interface DbChangedMessage {
	type: 'db:changed';
	table: string;
	operation: ChangeOperation;
	/** Full row data for the affected rows (matches Electron's notification pattern) */
	rows: Record<string, unknown>[];
	timestamp: number;
}

export interface DbErrorMessage {
	type: 'db:error';
	error: string;
}

export interface DialogResultMessage {
	type: 'dialog:result';
	id: string;
	cancelled: boolean;
	filePath?: string;
}

export interface DialogOpenSqliteResultMessage {
	type: 'dialog:openSqliteResult';
	id: string;
	success: true;
	filepath: string;
}

export interface DialogOpenSqliteErrorMessage {
	type: 'dialog:openSqliteResult';
	id: string;
	success: false;
}

export interface DialogSaveSqliteResultMessage {
	type: 'dialog:saveSqliteResult';
	id: string;
	success: true;
	filepath: string;
}

export interface DialogSaveSqliteErrorMessage {
	type: 'dialog:saveSqliteResult';
	id: string;
	success: false;
}

export interface FileReadResultMessage {
	type: 'file:readResult';
	id: string;
	success: true;
	content: string;
}

export interface FileReadErrorMessage {
	type: 'file:readResult';
	id: string;
	success: false;
	error: string;
}

export interface FileWriteResultMessage {
	type: 'file:writeResult';
	id: string;
	success: true;
}

export interface FileWriteErrorMessage {
	type: 'file:writeResult';
	id: string;
	success: false;
	error: string;
}

export interface FileCreateResultMessage {
	type: 'file:createResult';
	id: string;
	success: true;
}

export interface FileCreateErrorMessage {
	type: 'file:createResult';
	id: string;
	success: false;
	error: string;
}

export interface FileAppendResultMessage {
	type: 'file:appendResult';
	id: string;
	success: true;
}

export interface FileAppendErrorMessage {
	type: 'file:appendResult';
	id: string;
	success: false;
	error: string;
}

export interface FileMakeDirResultMessage {
	type: 'file:mkdirResult';
	id: string;
	success: true;
}

export interface FileMakeDirErrorMessage {
	type: 'file:mkdirResult';
	id: string;
	success: false;
	error: string;
}

export interface FileWriteBinaryResultMessage {
	type: 'file:writeBinaryResult';
	id: string;
	success: true;
}

export interface FileWriteBinaryErrorMessage {
	type: 'file:writeBinaryResult';
	id: string;
	success: false;
	error: string;
}

export interface FileRenameResultMessage {
	type: 'file:renameResult';
	id: string;
	success: true;
}

export interface FileRenameErrorMessage {
	type: 'file:renameResult';
	id: string;
	success: false;
	error: string;
}

export interface FileExistsResultMessage {
	type: 'file:existsResult';
	id: string;
	success: true;
	exists: boolean;
}

export interface FileExistsErrorMessage {
	type: 'file:existsResult';
	id: string;
	success: false;
	error: string;
}

export interface ScannerResultMessage {
	type: 'scanner:result';
	conversations: Array<{
		id: number;
		methods: Array<{
			name: string;
			type: 'condition' | 'action';
			exists: boolean;
		}>;
	}>;
}

export interface ScannedAction {
	name: string;
	category: string;
	filePath: string;
	lineNumber: number;
	parameters: Array<{
		name: string;
		type: string;
		optional: boolean;
		defaultValue?: string;
	}>;
}

export interface ScannedCondition {
	name: string;
	filePath: string;
	lineNumber: number;
	parameters: Array<{
		name: string;
		type: string;
		optional: boolean;
		defaultValue?: string;
	}>;
}

export interface ScannerResultsMessage {
	type: 'scanner:results';
	actions: ScannedAction[];
	conditions: ScannedCondition[];
}

export interface ScannerErrorMessage {
	type: 'scanner:error';
	error: string;
}

export interface RegistryUpdatedMessage {
	type: 'registryUpdated';
	actions: ScannedAction[];
	conditions: ScannedCondition[];
}

/**
 * Focus broadcast from extension to all panels.
 */
export interface FocusBroadcastMessage {
	type: 'focus:broadcast';
	table: FocusableTable;
	items: FocusItem[];
}

/**
 * Response with method body for preview.
 */
export interface CodeMethodResultMessage {
	type: 'code:methodResult';
	id: string;
	success: true;
	body: string;
	filePath: string;
	lineNumber: number;
}

export interface CodeMethodErrorMessage {
	type: 'code:methodResult';
	id: string;
	success: false;
	error: string;
}

/**
 * Response after creating a method stub.
 */
export interface CodeCreateResultMessage {
	type: 'code:createResult';
	id: string;
	success: boolean;
	error?: string;
}

/**
 * Response after delete confirmation (with diff preview).
 */
export interface CodeDeleteResultMessage {
	type: 'code:deleteResult';
	id: string;
	accepted: boolean;
	error?: string;
}

/**
 * Notification that a conversation code file changed.
 * Sent when file watcher detects changes.
 */
export interface CodeFileChangedMessage {
	type: 'code:fileChanged';
	conversationId: number;
}

export interface CodeGetMethodResultMessage {
	type: 'code:getMethodResult';
	id: string;
	success: true;
	methodBody: string;
}

export interface CodeGetMethodErrorMessage {
	type: 'code:getMethodResult';
	id: string;
	success: false;
	error: string;
}

export interface CodeCreateMethodResultMessage {
	type: 'code:createMethodResult';
	id: string;
	success: true;
}

export interface CodeCreateMethodErrorMessage {
	type: 'code:createMethodResult';
	id: string;
	success: false;
	error: string;
}

export interface CodeDeleteMethodResultMessage {
	type: 'code:deleteMethodResult';
	id: string;
	success: true;
	accepted: boolean;
}

export interface CodeDeleteMethodErrorMessage {
	type: 'code:deleteMethodResult';
	id: string;
	success: false;
	error: string;
}

/**
 * Response for silent batch method deletion (returns the deleted code for each method for undo).
 */
export interface CodeDeleteMethodsSilentResultMessage {
	type: 'code:deleteMethodsSilentResult';
	id: string;
	success: true;
	/** Map of method name to deleted code (includes attribute and body) */
	deletedMethods: Record<string, string>;
}

export interface CodeDeleteMethodsSilentErrorMessage {
	type: 'code:deleteMethodsSilentResult';
	id: string;
	success: false;
	error: string;
}

/**
 * Response for method restoration.
 */
export interface CodeRestoreMethodResultMessage {
	type: 'code:restoreMethodResult';
	id: string;
	success: true;
}

export interface CodeRestoreMethodErrorMessage {
	type: 'code:restoreMethodResult';
	id: string;
	success: false;
	error: string;
}

/**
 * Response for file deletion (returns the deleted content for undo).
 */
export interface CodeDeleteFileResultMessage {
	type: 'code:deleteFileResult';
	id: string;
	success: true;
	/** The full file content that was deleted */
	deletedContent: string;
}

export interface CodeDeleteFileErrorMessage {
	type: 'code:deleteFileResult';
	id: string;
	success: false;
	error: string;
}

/**
 * Response for file restoration.
 */
export interface CodeRestoreFileResultMessage {
	type: 'code:restoreFileResult';
	id: string;
	success: true;
}

export interface CodeRestoreFileErrorMessage {
	type: 'code:restoreFileResult';
	id: string;
	success: false;
	error: string;
}

export interface ThemeChangedMessage {
	type: 'theme:changed';
	isDark: boolean;
}

/**
 * Union type of all messages sent FROM Extension TO UI
 */
export type IncomingMessage =
	| ConnectedMessage
	| DisconnectedMessage
	| DbQueryResultMessage
	| DbQueryErrorMessage
	| DbExecResultMessage
	| DbExecErrorMessage
	| DbRunResultMessage
	| DbRunErrorMessage
	| DbBatchResultMessage
	| DbBatchErrorMessage
	| DbTransactionBeginResultMessage
	| DbTransactionBeginErrorMessage
	| DbTransactionCommitResultMessage
	| DbTransactionCommitErrorMessage
	| DbTransactionRollbackResultMessage
	| DbTransactionRollbackErrorMessage
	| DbErrorMessage
	| DbChangedMessage
	| DialogResultMessage
	| DialogOpenSqliteResultMessage
	| DialogOpenSqliteErrorMessage
	| DialogSaveSqliteResultMessage
	| DialogSaveSqliteErrorMessage
	| FileReadResultMessage
	| FileReadErrorMessage
	| FileWriteResultMessage
	| FileWriteErrorMessage
	| FileCreateResultMessage
	| FileCreateErrorMessage
	| FileAppendResultMessage
	| FileAppendErrorMessage
	| FileMakeDirResultMessage
	| FileMakeDirErrorMessage
	| FileWriteBinaryResultMessage
	| FileWriteBinaryErrorMessage
	| FileRenameResultMessage
	| FileRenameErrorMessage
	| FileExistsResultMessage
	| FileExistsErrorMessage
	| ScannerResultMessage
	| ScannerResultsMessage
	| ScannerErrorMessage
	| RegistryUpdatedMessage
	| FocusBroadcastMessage
	| CodeMethodResultMessage
	| CodeMethodErrorMessage
	| CodeCreateResultMessage
	| CodeDeleteResultMessage
	| CodeFileChangedMessage
	| CodeGetMethodResultMessage
	| CodeGetMethodErrorMessage
	| CodeCreateMethodResultMessage
	| CodeCreateMethodErrorMessage
	| CodeDeleteMethodResultMessage
	| CodeDeleteMethodErrorMessage
	| CodeDeleteMethodsSilentResultMessage
	| CodeDeleteMethodsSilentErrorMessage
	| CodeRestoreMethodResultMessage
	| CodeRestoreMethodErrorMessage
	| CodeDeleteFileResultMessage
	| CodeDeleteFileErrorMessage
	| CodeRestoreFileResultMessage
	| CodeRestoreFileErrorMessage
	| ThemeChangedMessage;

// ============================================================================
// Bridge Event Types
// ============================================================================

export interface DataChangeEvent {
	table: string;
	operation: ChangeOperation;
	/** Full row data for the affected rows (matches Electron's notification pattern) */
	rows: Record<string, unknown>[];
	timestamp: number;
}

export interface FocusChangeEvent {
	table: FocusableTable;
	items: FocusItem[];
}

export interface CodeFileChangeEvent {
	conversationId: number;
}

export interface BridgeEvents {
	connected: (dbType: DatabaseType) => void;
	disconnected: () => void;
	error: (error: string) => void;
	registryUpdated: (actions: ScannedAction[], conditions: ScannedCondition[]) => void;
	dataChanged: (event: DataChangeEvent) => void;
	focusChanged: (event: FocusChangeEvent) => void;
	codeFileChanged: (event: CodeFileChangeEvent) => void;
	themeChanged: (isDark: boolean) => void;
}

export type BridgeEventName = keyof BridgeEvents;
