/**
 * Message types for communication between UI webview and extension backend.
 * Used by both the UI package and IDE plugin packages (VSCode, Rider, etc.)
 */

import type { DatabaseType, DatabaseConfig, DbNotificationMeta, DbBatchStatement, TransactionContext } from './database.js';

// Re-export for convenience
export type { DbNotificationMeta, DbBatchStatement };

// ============================================================================
// Messages FROM UI TO Extension
// ============================================================================

export interface ReadyMessage {
	type: 'ready';
}

export interface DbQueryMessage {
	type: 'db:query';
	id: string;
	sql: string;
	params?: unknown[];
	/** Optional transaction context */
	context?: TransactionContext;
}

/**
 * Execute DDL statements (CREATE, ALTER, DROP).
 * No parameters supported - for DML with params, use DbRunMessage.
 */
export interface DbExecMessage {
	type: 'db:exec';
	id: string;
	sql: string;
	/** Optional notification metadata (auto-generated by CRUD methods) */
	notificationMeta?: DbNotificationMeta;
	/** Optional transaction context */
	context?: TransactionContext;
}

/**
 * Execute DML statements (INSERT, UPDATE, DELETE).
 */
export interface DbRunMessage {
	type: 'db:run';
	id: string;
	sql: string;
	params?: unknown[];
	/** If true, expects SQL to have RETURNING clause and will return rows */
	returning?: boolean;
	/** Optional notification metadata (auto-generated by CRUD methods) */
	notificationMeta?: DbNotificationMeta;
	/** Optional transaction context */
	context?: TransactionContext;
}

/** Request to open a raw database connection (no validation) */
export interface DbOpenMessage {
	type: 'db:open';
	id: string;
	config: DatabaseConfig;
}

/** Response after raw connection attempt */
export interface DbOpenResultMessage {
	type: 'db:openResult';
	id: string;
	success: boolean;
	error?: string;
}

/** Request to close the database connection */
export interface DbCloseMessage {
	type: 'db:close';
	id: string;
}

/** Response after close attempt */
export interface DbCloseResultMessage {
	type: 'db:closeResult';
	id: string;
	success: boolean;
	error?: string;
}

/**
 * Request to start change notifications (LISTEN/NOTIFY for PostgreSQL).
 * Sent by the UI after schema validation/initialization completes.
 */
export interface DbStartNotificationsMessage {
	type: 'db:startNotifications';
	id: string;
}

/** Response after starting change notifications */
export interface DbStartNotificationsResultMessage {
	type: 'db:startNotificationsResult';
	id: string;
	success: boolean;
	error?: string;
}

export interface DialogOpenSqliteMessage {
	type: 'dialog:openSqlite';
	id: string;
}

export interface DialogSaveSqliteMessage {
	type: 'dialog:saveSqlite';
	id: string;
}

export interface DialogOpenCsvMessage {
	type: 'dialog:openCsv';
	id: string;
}

export interface DialogSaveCsvMessage {
	type: 'dialog:saveCsv';
	id: string;
	defaultFilename?: string;
}

export interface DialogSelectFolderMessage {
	type: 'dialog:selectFolder';
	id: string;
	title?: string;
}

export interface FileReadMessage {
	type: 'file:read';
	id: string;
	filePath: string;
}

export interface FileWriteMessage {
	type: 'file:write';
	id: string;
	filePath: string;
	content: string;
}

export interface FileCreateMessage {
	type: 'file:create';
	id: string;
	filePath: string;
}

export interface FileAppendMessage {
	type: 'file:append';
	id: string;
	filePath: string;
	content: string;
}

export interface FileMakeDirMessage {
	type: 'file:mkdir';
	id: string;
	dirPath: string;
}

export interface FileWriteBinaryMessage {
	type: 'file:writeBinary';
	id: string;
	filePath: string;
	/** Binary content as base64-encoded string */
	contentBase64: string;
}

export interface FileRenameMessage {
	type: 'file:rename';
	id: string;
	oldPath: string;
	newPath: string;
}

export interface FileExistsMessage {
	type: 'file:exists';
	id: string;
	filePath: string;
}

export interface ScannerScanMessage {
	type: 'scanner:scan';
}

export interface EditorOpenFileMessage {
	type: 'editor:openFile';
	filePath: string;
	lineNumber?: number;
}

export interface EditorCreateFileMessage {
	type: 'editor:createFile';
	filePath: string;
	content: string;
}

/**
 * Request to get a method body from a conversation code file.
 * Uses IDE symbol provider to find the method.
 */
export interface CodeGetMethodMessage {
	type: 'code:getMethod';
	id: string;
	conversationId: number;
	methodName: string; // e.g., "Node_123_Condition"
	/** File extension including the dot (e.g., '.cs', '.cpp', '.gd') */
	fileExtension: string;
	/** Code template type for language-specific behavior */
	template: CodeTemplateType;
}

/**
 * Code template types for different game engines.
 */
export type CodeTemplateType = 'unity' | 'godot' | 'unreal';

/**
 * Request to create a method stub and open it in the IDE.
 * The UI generates the code; the IDE plugin just writes it.
 */
export interface CodeCreateMethodMessage {
	type: 'code:createMethod';
	id: string;
	conversationId: number;
	methodName: string;
	/** File extension including the dot (e.g., '.cs', '.cpp', '.gd') */
	fileExtension: string;
	/** Code template type for language-specific behavior */
	template: CodeTemplateType;
	/** Generated method stub code */
	methodStub: string;
	/** Generated file content (used when creating a new file) */
	fileContent: string;
}

/**
 * Request to delete a method with diff preview (interactive).
 * Returns whether the user accepted or rejected the deletion.
 */
export interface CodeDeleteMethodMessage {
	type: 'code:deleteMethod';
	id: string;
	conversationId: number;
	methodName: string;
	/** File extension including the dot (e.g., '.cs', '.cpp', '.gd') */
	fileExtension: string;
	/** Code template type for language-specific behavior */
	template: CodeTemplateType;
}

/**
 * Request to delete multiple methods without confirmation (programmatic).
 * Used when deleting nodes - returns the deleted code for each method for undo.
 * Methods are deleted in a single file operation to avoid stale symbol issues.
 */
export interface CodeDeleteMethodsSilentMessage {
	type: 'code:deleteMethodsSilent';
	id: string;
	conversationId: number;
	methodNames: string[];
	/** File extension including the dot (e.g., '.cs', '.cpp', '.gd') */
	fileExtension: string;
	/** Code template type for language-specific behavior */
	template: CodeTemplateType;
}

/**
 * Request to restore a previously deleted method.
 * Used for undo after node deletion.
 */
export interface CodeRestoreMethodMessage {
	type: 'code:restoreMethod';
	id: string;
	conversationId: number;
	methodName: string;
	/** The method code to restore (includes attribute and body) */
	code: string;
	/** File extension including the dot (e.g., '.cs', '.cpp', '.gd') */
	fileExtension: string;
	/** Code template type for language-specific behavior */
	template: CodeTemplateType;
	/** Generated file content (used when recreating a deleted file) */
	fileContent: string;
}

/**
 * Request to delete an entire conversation code file.
 * Used when permanently deleting a conversation.
 */
export interface CodeDeleteFileMessage {
	type: 'code:deleteFile';
	id: string;
	conversationId: number;
	/** File extension including the dot (e.g., '.cs', '.cpp', '.gd') */
	fileExtension: string;
	/** Code template type for language-specific behavior */
	template: CodeTemplateType;
}

/**
 * Request to restore an entire conversation code file.
 * Used for undo after conversation deletion.
 */
export interface CodeRestoreFileMessage {
	type: 'code:restoreFile';
	id: string;
	conversationId: number;
	content: string;
	/** File extension including the dot (e.g., '.cs', '.cpp', '.gd') */
	fileExtension: string;
	/** Code template type for language-specific behavior */
	template: CodeTemplateType;
}

/**
 * Request to open a method in the IDE (go to symbol).
 */
export interface CodeOpenMethodMessage {
	type: 'code:openMethod';
	conversationId: number;
	methodName: string;
	/** File extension including the dot (e.g., '.cs', '.cpp', '.gd') */
	fileExtension: string;
	/** Code template type for language-specific behavior */
	template: CodeTemplateType;
}

/**
 * Request to set up file watcher for code files.
 * Sent by UI when code output folder or file extension changes.
 * Pass null folderPath to clear the watcher.
 */
export interface CodeWatchFolderMessage {
	type: 'code:watchFolder';
	/** Relative path to the code output folder, or null to clear */
	folderPath: string | null;
	/** File extension to watch (e.g., '.cs' or '.cpp'), defaults to '.cs' */
	fileExtension?: string;
}

/**
 * Request to set up file watcher for the snapshot output folder.
 * Watches for command.tmp files written by game engine plugins (Unity, Godot).
 * Pass null to clear the watcher.
 */
export interface SnapshotWatchFolderMessage {
	type: 'snapshot:watchFolder';
	/** Relative path to the snapshot output folder, or null to clear */
	folderPath: string | null;
}

// ============================================================================
// Google Sheets Messages (UI → Extension)
// ============================================================================

/**
 * Store Google API credentials in SecretStorage.
 */
export interface GoogleSheetsSetCredentialsMessage {
	type: 'googleSheets:setCredentials';
	id: string;
	clientId: string;
	clientSecret: string;
	apiKey: string;
}

/**
 * Check if Google API credentials are stored.
 * Returns hasCredentials (boolean), not the actual values.
 */
export interface GoogleSheetsGetCredentialsMessage {
	type: 'googleSheets:getCredentials';
	id: string;
}

/**
 * Initiate Google OAuth sign-in flow.
 * Opens browser for authentication.
 */
export interface GoogleSheetsSignInMessage {
	type: 'googleSheets:signIn';
	id: string;
}

/**
 * Sign out from Google Sheets.
 * Clears stored OAuth tokens.
 */
export interface GoogleSheetsSignOutMessage {
	type: 'googleSheets:signOut';
	id: string;
}

/**
 * Get current Google Sheets authentication status.
 */
export interface GoogleSheetsGetStatusMessage {
	type: 'googleSheets:getStatus';
	id: string;
}

/**
 * Open browser with Google Picker to select a spreadsheet.
 */
export interface GoogleSheetsSelectSpreadsheetMessage {
	type: 'googleSheets:selectSpreadsheet';
	id: string;
}

/**
 * Clear the currently selected spreadsheet.
 */
export interface GoogleSheetsClearSpreadsheetMessage {
	type: 'googleSheets:clearSpreadsheet';
	id: string;
}

/**
 * Push localization data to the configured Google Sheets spreadsheet.
 */
export interface GoogleSheetsPushMessage {
	type: 'googleSheets:push';
	id: string;
	/** The spreadsheet ID to push to */
	spreadsheetId: string;
	/** CSV-formatted data to push */
	data: string;
}

/**
 * Pull localization data from the configured Google Sheets spreadsheet.
 */
export interface GoogleSheetsPullMessage {
	type: 'googleSheets:pull';
	id: string;
	/** The spreadsheet ID to pull from */
	spreadsheetId: string;
}

export type NotificationLevel = 'info' | 'warning' | 'error';

/**
 * Operation phases for long-running operations like CSV import/export
 * and Google Sheets push/pull.
 */
export type OperationPhase =
	| 'preparing'
	| 'validating'
	| 'processing'
	| 'uploading'
	| 'downloading'
	| 'complete'
	| 'failed'
	| 'cancelled';

export interface NotifyMessage {
	type: 'notify';
	level: NotificationLevel;
	message: string;
	detail?: string;
}

export interface StatusMessage {
	type: 'status';
	message: string;
	timeoutMs?: number;
}

/**
 * Request to open an external URL in the system browser.
 */
export interface OpenExternalMessage {
	type: 'openExternal';
	url: string;
}

/**
 * Focus/selection types for cross-panel synchronization.
 */
// Plural forms used by internal focus system
export type FocusableTablePlural = 'conversations' | 'nodes' | 'edges' | 'actors' | 'locales' | 'localizations';
// Singular forms used by game engine IPC commands
export type FocusableTableSingular = 'conversation' | 'actor' | 'locale' | 'localization';
// Combined type for all focusable tables
export type FocusableTable = FocusableTablePlural | FocusableTableSingular;

export interface FocusItem {
	id: number;
	payload?: Record<string, unknown>;
}

export interface FocusSetMessage {
	type: 'focus:set';
	table: FocusableTable;
	items: FocusItem[];
}

export interface DbBatchMessage {
	type: 'db:batch';
	id: string;
	statements: DbBatchStatement[];
}

export interface DbTransactionBeginMessage {
	type: 'db:transaction:begin';
	id: string;
}

export interface DbTransactionCommitMessage {
	type: 'db:transaction:commit';
	id: string;
	/** Transaction context returned from begin */
	context: TransactionContext;
}

export interface DbTransactionRollbackMessage {
	type: 'db:transaction:rollback';
	id: string;
	/** Transaction context returned from begin */
	context: TransactionContext;
}

/**
 * Union type of all messages sent FROM UI TO Extension
 */
export type OutgoingMessage =
	| ReadyMessage
	| DbQueryMessage
	| DbExecMessage
	| DbRunMessage
	| DbBatchMessage
	| DbTransactionBeginMessage
	| DbTransactionCommitMessage
	| DbTransactionRollbackMessage
	| DbOpenMessage
	| DbCloseMessage
	| DbStartNotificationsMessage
	| DialogOpenSqliteMessage
	| DialogSaveSqliteMessage
	| DialogOpenCsvMessage
	| DialogSaveCsvMessage
	| DialogSelectFolderMessage
	| FileReadMessage
	| FileWriteMessage
	| FileCreateMessage
	| FileAppendMessage
	| FileMakeDirMessage
	| FileWriteBinaryMessage
	| FileRenameMessage
	| FileExistsMessage
	| ScannerScanMessage
	| EditorOpenFileMessage
	| EditorCreateFileMessage
	| NotifyMessage
	| StatusMessage
	| FocusSetMessage
	| CodeGetMethodMessage
	| CodeCreateMethodMessage
	| CodeDeleteMethodMessage
	| CodeDeleteMethodsSilentMessage
	| CodeRestoreMethodMessage
	| CodeDeleteFileMessage
	| CodeRestoreFileMessage
	| CodeOpenMethodMessage
	| CodeWatchFolderMessage
	| SnapshotWatchFolderMessage
	| GoogleSheetsSetCredentialsMessage
	| GoogleSheetsGetCredentialsMessage
	| GoogleSheetsSignInMessage
	| GoogleSheetsSignOutMessage
	| GoogleSheetsGetStatusMessage
	| GoogleSheetsSelectSpreadsheetMessage
	| GoogleSheetsClearSpreadsheetMessage
	| GoogleSheetsPushMessage
	| GoogleSheetsPullMessage
	| OpenExternalMessage;

// ============================================================================
// Messages FROM Extension TO UI
// ============================================================================

export interface ConnectedMessage {
	type: 'connected';
	dbType: DatabaseType;
}

export interface DisconnectedMessage {
	type: 'disconnected';
	dbType: DatabaseType | null;
}

export interface DbQueryResultMessage {
	type: 'db:queryResult';
	id: string;
	success: true;
	data: unknown[];
}

export interface DbQueryErrorMessage {
	type: 'db:queryResult';
	id: string;
	success: false;
	error: string;
}

export interface DbExecResultMessage {
	type: 'db:execResult';
	id: string;
	success: true;
}

export interface DbExecErrorMessage {
	type: 'db:execResult';
	id: string;
	success: false;
	error: string;
}

export interface DbRunResultMessage {
	type: 'db:runResult';
	id: string;
	success: true;
	/** Last inserted row ID (only populated if a numeric 'id' column was returned) */
	lastID?: number;
	changes: number;
	/** Rows returned from RETURNING clause */
	rows: unknown[];
}

export interface DbRunErrorMessage {
	type: 'db:runResult';
	id: string;
	success: false;
	error: string;
}

export interface DbBatchResultMessage {
	type: 'db:batchResult';
	id: string;
	success: true;
	/** Last inserted IDs for INSERT statements */
	insertIds?: number[];
}

export interface DbBatchErrorMessage {
	type: 'db:batchResult';
	id: string;
	success: false;
	error: string;
}

export interface DbTransactionBeginResultMessage {
	type: 'db:transactionBeginResult';
	id: string;
	success: true;
	context: TransactionContext;
}

export interface DbTransactionBeginErrorMessage {
	type: 'db:transactionBeginResult';
	id: string;
	success: false;
	error: string;
}

export interface DbTransactionCommitResultMessage {
	type: 'db:transactionCommitResult';
	id: string;
	success: true;
}

export interface DbTransactionCommitErrorMessage {
	type: 'db:transactionCommitResult';
	id: string;
	success: false;
	error: string;
}

export interface DbTransactionRollbackResultMessage {
	type: 'db:transactionRollbackResult';
	id: string;
	success: true;
}

export interface DbTransactionRollbackErrorMessage {
	type: 'db:transactionRollbackResult';
	id: string;
	success: false;
	error: string;
}

export type ChangeOperation = 'insert' | 'update' | 'delete' | 'alter';

export interface DbChangedMessage {
	type: 'db:changed';
	table: string;
	operation: ChangeOperation;
	/** Full row data for the affected rows (matches Electron's notification pattern) */
	rows: Record<string, unknown>[];
	timestamp: number;
}

export interface DbErrorMessage {
	type: 'db:error';
	error: string;
}

export interface DialogResultMessage {
	type: 'dialog:result';
	id: string;
	cancelled: boolean;
	filePath?: string;
}

export interface DialogOpenSqliteResultMessage {
	type: 'dialog:openSqliteResult';
	id: string;
	success: true;
	filepath: string;
}

export interface DialogOpenSqliteErrorMessage {
	type: 'dialog:openSqliteResult';
	id: string;
	success: false;
}

export interface DialogSaveSqliteResultMessage {
	type: 'dialog:saveSqliteResult';
	id: string;
	success: true;
	filepath: string;
}

export interface DialogSaveSqliteErrorMessage {
	type: 'dialog:saveSqliteResult';
	id: string;
	success: false;
}

export interface FileReadResultMessage {
	type: 'file:readResult';
	id: string;
	success: true;
	content: string;
}

export interface FileReadErrorMessage {
	type: 'file:readResult';
	id: string;
	success: false;
	error: string;
}

export interface FileWriteResultMessage {
	type: 'file:writeResult';
	id: string;
	success: true;
}

export interface FileWriteErrorMessage {
	type: 'file:writeResult';
	id: string;
	success: false;
	error: string;
}

export interface FileCreateResultMessage {
	type: 'file:createResult';
	id: string;
	success: true;
}

export interface FileCreateErrorMessage {
	type: 'file:createResult';
	id: string;
	success: false;
	error: string;
}

export interface FileAppendResultMessage {
	type: 'file:appendResult';
	id: string;
	success: true;
}

export interface FileAppendErrorMessage {
	type: 'file:appendResult';
	id: string;
	success: false;
	error: string;
}

export interface FileMakeDirResultMessage {
	type: 'file:mkdirResult';
	id: string;
	success: true;
}

export interface FileMakeDirErrorMessage {
	type: 'file:mkdirResult';
	id: string;
	success: false;
	error: string;
}

export interface FileWriteBinaryResultMessage {
	type: 'file:writeBinaryResult';
	id: string;
	success: true;
}

export interface FileWriteBinaryErrorMessage {
	type: 'file:writeBinaryResult';
	id: string;
	success: false;
	error: string;
}

export interface FileRenameResultMessage {
	type: 'file:renameResult';
	id: string;
	success: true;
}

export interface FileRenameErrorMessage {
	type: 'file:renameResult';
	id: string;
	success: false;
	error: string;
}

export interface FileExistsResultMessage {
	type: 'file:existsResult';
	id: string;
	success: true;
	exists: boolean;
}

export interface FileExistsErrorMessage {
	type: 'file:existsResult';
	id: string;
	success: false;
	error: string;
}

export interface ScannerResultMessage {
	type: 'scanner:result';
	conversations: Array<{
		id: number;
		methods: Array<{
			name: string;
			type: 'condition' | 'action';
			exists: boolean;
		}>;
	}>;
}

export interface ScannedAction {
	name: string;
	category: string;
	filePath: string;
	lineNumber: number;
	parameters: Array<{
		name: string;
		type: string;
		optional: boolean;
		defaultValue?: string;
	}>;
}

export interface ScannedCondition {
	name: string;
	filePath: string;
	lineNumber: number;
	parameters: Array<{
		name: string;
		type: string;
		optional: boolean;
		defaultValue?: string;
	}>;
}

export interface ScannerResultsMessage {
	type: 'scanner:results';
	actions: ScannedAction[];
	conditions: ScannedCondition[];
}

export interface ScannerErrorMessage {
	type: 'scanner:error';
	error: string;
}

export interface RegistryUpdatedMessage {
	type: 'registryUpdated';
	actions: ScannedAction[];
	conditions: ScannedCondition[];
}

/**
 * Focus broadcast from extension to all panels.
 */
export interface FocusBroadcastMessage {
	type: 'focus:broadcast';
	table: FocusableTable;
	items: FocusItem[];
}

/**
 * Response with method body for preview.
 */
export interface CodeMethodResultMessage {
	type: 'code:methodResult';
	id: string;
	success: true;
	/** Method body (signature + implementation), used for preview display */
	body: string;
	/** Full method text including preceding attributes, used for undo/restore */
	fullText: string;
	filePath: string;
	lineNumber: number;
}

export interface CodeMethodErrorMessage {
	type: 'code:methodResult';
	id: string;
	success: false;
	error: string;
}

/**
 * Response after creating a method stub.
 */
export interface CodeCreateResultMessage {
	type: 'code:createResult';
	id: string;
	success: boolean;
	error?: string;
}

/**
 * Response after delete confirmation (with diff preview).
 */
export interface CodeDeleteResultMessage {
	type: 'code:deleteResult';
	id: string;
	accepted: boolean;
	error?: string;
}

/**
 * Notification that a conversation code file changed.
 * Sent when file watcher detects changes.
 */
export interface CodeFileChangedMessage {
	type: 'code:fileChanged';
	conversationId: number;
}

export interface CodeGetMethodResultMessage {
	type: 'code:getMethodResult';
	id: string;
	success: true;
	methodBody: string;
}

export interface CodeGetMethodErrorMessage {
	type: 'code:getMethodResult';
	id: string;
	success: false;
	error: string;
}

export interface CodeCreateMethodResultMessage {
	type: 'code:createMethodResult';
	id: string;
	success: true;
}

export interface CodeCreateMethodErrorMessage {
	type: 'code:createMethodResult';
	id: string;
	success: false;
	error: string;
}

export interface CodeDeleteMethodResultMessage {
	type: 'code:deleteMethodResult';
	id: string;
	success: true;
	accepted: boolean;
}

export interface CodeDeleteMethodErrorMessage {
	type: 'code:deleteMethodResult';
	id: string;
	success: false;
	error: string;
}

/**
 * Response for silent batch method deletion (returns the deleted code for each method for undo).
 */
export interface CodeDeleteMethodsSilentResultMessage {
	type: 'code:deleteMethodsSilentResult';
	id: string;
	success: true;
	/** Map of method name to deleted code (includes attribute and body) */
	deletedMethods: Record<string, string>;
}

export interface CodeDeleteMethodsSilentErrorMessage {
	type: 'code:deleteMethodsSilentResult';
	id: string;
	success: false;
	error: string;
}

/**
 * Response for method restoration.
 */
export interface CodeRestoreMethodResultMessage {
	type: 'code:restoreMethodResult';
	id: string;
	success: true;
}

export interface CodeRestoreMethodErrorMessage {
	type: 'code:restoreMethodResult';
	id: string;
	success: false;
	error: string;
}

/**
 * Response for file deletion (returns the deleted content for undo).
 */
export interface CodeDeleteFileResultMessage {
	type: 'code:deleteFileResult';
	id: string;
	success: true;
	/** The full file content that was deleted */
	deletedContent: string;
}

export interface CodeDeleteFileErrorMessage {
	type: 'code:deleteFileResult';
	id: string;
	success: false;
	error: string;
}

/**
 * Response for file restoration.
 */
export interface CodeRestoreFileResultMessage {
	type: 'code:restoreFileResult';
	id: string;
	success: true;
}

export interface CodeRestoreFileErrorMessage {
	type: 'code:restoreFileResult';
	id: string;
	success: false;
	error: string;
}

export interface ThemeChangedMessage {
	type: 'theme:changed';
	isDark: boolean;
}

/**
 * Edit command messages sent from IDE to UI.
 * These are triggered by keyboard shortcuts intercepted by the IDE plugin
 * to prevent conflicts with the IDE's native undo/redo/save.
 */
export interface EditUndoMessage {
	type: 'edit:undo';
}

export interface EditRedoMessage {
	type: 'edit:redo';
}

export interface EditSaveMessage {
	type: 'edit:save';
}

// ============================================================================
// Google Sheets Messages (Extension → UI)
// ============================================================================

/**
 * Spreadsheet info returned from selection or status.
 */
export interface GoogleSheetsSpreadsheetInfo {
	id: string;
	name: string;
	url: string;
}

export interface GoogleSheetsSetCredentialsResultMessage {
	type: 'googleSheets:setCredentialsResult';
	id: string;
	success: boolean;
}

export interface GoogleSheetsGetCredentialsResultMessage {
	type: 'googleSheets:getCredentialsResult';
	id: string;
	hasCredentials: boolean;
}

export interface GoogleSheetsSignInResultMessage {
	type: 'googleSheets:signInResult';
	id: string;
	success: true;
	email: string;
}

export interface GoogleSheetsSignInErrorMessage {
	type: 'googleSheets:signInResult';
	id: string;
	success: false;
	error: string;
}

export interface GoogleSheetsSignOutResultMessage {
	type: 'googleSheets:signOutResult';
	id: string;
	success: true;
}

export interface GoogleSheetsSignOutErrorMessage {
	type: 'googleSheets:signOutResult';
	id: string;
	success: false;
	error: string;
}

export interface GoogleSheetsStatusResultMessage {
	type: 'googleSheets:statusResult';
	id: string;
	authenticated: boolean;
	email?: string;
}

export interface GoogleSheetsSelectSpreadsheetResultMessage {
	type: 'googleSheets:selectSpreadsheetResult';
	id: string;
	success: true;
	spreadsheet: GoogleSheetsSpreadsheetInfo;
}

export interface GoogleSheetsSelectSpreadsheetErrorMessage {
	type: 'googleSheets:selectSpreadsheetResult';
	id: string;
	success: false;
	/** Error message, or 'cancelled' if user closed picker without selecting */
	error: string;
}

export interface GoogleSheetsClearSpreadsheetResultMessage {
	type: 'googleSheets:clearSpreadsheetResult';
	id: string;
	success: true;
}

export interface GoogleSheetsPushResultMessage {
	type: 'googleSheets:pushResult';
	id: string;
	success: true;
}

export interface GoogleSheetsPushErrorMessage {
	type: 'googleSheets:pushResult';
	id: string;
	success: false;
	error: string;
}

export interface GoogleSheetsPullResultMessage {
	type: 'googleSheets:pullResult';
	id: string;
	success: true;
	/** CSV-formatted data from the spreadsheet */
	data: string;
}

export interface GoogleSheetsPullErrorMessage {
	type: 'googleSheets:pullResult';
	id: string;
	success: false;
	error: string;
}

/**
 * Broadcast when Google Sheets authentication state changes.
 * Sent when user signs in or out.
 */
export interface GoogleSheetsAuthChangedMessage {
	type: 'googleSheets:authChanged';
	authenticated: boolean;
	email?: string;
}

/**
 * Broadcast when the selected spreadsheet changes.
 * Sent when user selects or clears a spreadsheet.
 */
export interface GoogleSheetsSpreadsheetChangedMessage {
	type: 'googleSheets:spreadsheetChanged';
	spreadsheet: GoogleSheetsSpreadsheetInfo | null;
}

/**
 * Union type of all messages sent FROM Extension TO UI
 */
export type IncomingMessage =
	| ConnectedMessage
	| DisconnectedMessage
	| DbQueryResultMessage
	| DbQueryErrorMessage
	| DbExecResultMessage
	| DbExecErrorMessage
	| DbRunResultMessage
	| DbRunErrorMessage
	| DbBatchResultMessage
	| DbBatchErrorMessage
	| DbTransactionBeginResultMessage
	| DbTransactionBeginErrorMessage
	| DbTransactionCommitResultMessage
	| DbTransactionCommitErrorMessage
	| DbTransactionRollbackResultMessage
	| DbTransactionRollbackErrorMessage
	| DbOpenResultMessage
	| DbCloseResultMessage
	| DbStartNotificationsResultMessage
	| DbErrorMessage
	| DbChangedMessage
	| DialogResultMessage
	| DialogOpenSqliteResultMessage
	| DialogOpenSqliteErrorMessage
	| DialogSaveSqliteResultMessage
	| DialogSaveSqliteErrorMessage
	| FileReadResultMessage
	| FileReadErrorMessage
	| FileWriteResultMessage
	| FileWriteErrorMessage
	| FileCreateResultMessage
	| FileCreateErrorMessage
	| FileAppendResultMessage
	| FileAppendErrorMessage
	| FileMakeDirResultMessage
	| FileMakeDirErrorMessage
	| FileWriteBinaryResultMessage
	| FileWriteBinaryErrorMessage
	| FileRenameResultMessage
	| FileRenameErrorMessage
	| FileExistsResultMessage
	| FileExistsErrorMessage
	| ScannerResultMessage
	| ScannerResultsMessage
	| ScannerErrorMessage
	| RegistryUpdatedMessage
	| FocusBroadcastMessage
	| CodeMethodResultMessage
	| CodeMethodErrorMessage
	| CodeCreateResultMessage
	| CodeDeleteResultMessage
	| CodeFileChangedMessage
	| CodeGetMethodResultMessage
	| CodeGetMethodErrorMessage
	| CodeCreateMethodResultMessage
	| CodeCreateMethodErrorMessage
	| CodeDeleteMethodResultMessage
	| CodeDeleteMethodErrorMessage
	| CodeDeleteMethodsSilentResultMessage
	| CodeDeleteMethodsSilentErrorMessage
	| CodeRestoreMethodResultMessage
	| CodeRestoreMethodErrorMessage
	| CodeDeleteFileResultMessage
	| CodeDeleteFileErrorMessage
	| CodeRestoreFileResultMessage
	| CodeRestoreFileErrorMessage
	| ThemeChangedMessage
	| EditUndoMessage
	| EditRedoMessage
	| EditSaveMessage
	| GoogleSheetsSetCredentialsResultMessage
	| GoogleSheetsGetCredentialsResultMessage
	| GoogleSheetsSignInResultMessage
	| GoogleSheetsSignInErrorMessage
	| GoogleSheetsSignOutResultMessage
	| GoogleSheetsSignOutErrorMessage
	| GoogleSheetsStatusResultMessage
	| GoogleSheetsSelectSpreadsheetResultMessage
	| GoogleSheetsSelectSpreadsheetErrorMessage
	| GoogleSheetsClearSpreadsheetResultMessage
	| GoogleSheetsPushResultMessage
	| GoogleSheetsPushErrorMessage
	| GoogleSheetsPullResultMessage
	| GoogleSheetsPullErrorMessage
	| GoogleSheetsAuthChangedMessage
	| GoogleSheetsSpreadsheetChangedMessage;

// ============================================================================
// Bridge Event Types
// ============================================================================

export interface DataChangeEvent {
	table: string;
	operation: ChangeOperation;
	/** Full row data for the affected rows (matches Electron's notification pattern) */
	rows: Record<string, unknown>[];
	timestamp: number;
}

export interface FocusChangeEvent {
	table: FocusableTable;
	items: FocusItem[];
}

export interface CodeFileChangeEvent {
	conversationId: number;
}

export interface BridgeEvents {
	connected: (dbType: DatabaseType) => void;
	disconnected: () => void;
	error: (error: string) => void;
	registryUpdated: (actions: ScannedAction[], conditions: ScannedCondition[]) => void;
	dataChanged: (event: DataChangeEvent) => void;
	focusChanged: (event: FocusChangeEvent) => void;
	codeFileChanged: (event: CodeFileChangeEvent) => void;
	themeChanged: (isDark: boolean) => void;
	/** Edit commands from IDE (keyboard shortcuts intercepted by plugin) */
	editUndo: () => void;
	editRedo: () => void;
	editSave: () => void;
	/** Google Sheets authentication state changed */
	googleSheetsAuthChanged: (authenticated: boolean, email?: string) => void;
	/** Google Sheets selected spreadsheet changed */
	googleSheetsSpreadsheetChanged: (spreadsheet: GoogleSheetsSpreadsheetInfo | null) => void;
}

export type BridgeEventName = keyof BridgeEvents;
