import { ACTORS_DEFAULT_COLOR } from '@lib/constants/settings';
import { localeIdToColumn } from '@lib/utility/locale';
import {
    ACTOR_LOCALIZATION_TABLE_NAME,
    DATABASE_TABLE_NAMES,
    PROGRAMMING_LANGUAGE_NAMES,
    ROUTINE_TYPES,
    ROUTINE_TYPE_ID_DEFAULT,
    ROUTINE_TYPE_ID_IMPORTS,
    TABLE_NAME_ACTORS,
    TABLE_NAME_ACTOR_PRINCIPAL,
    TABLE_NAME_AUTO_COMPLETES,
    TABLE_NAME_CONVERSATIONS,
    TABLE_NAME_LOCALES,
    TABLE_NAME_LOCALE_PRINCIPAL,
    TABLE_NAME_LOCALIZATIONS,
    TABLE_NAME_LOCALIZATION_TABLES,
    TABLE_NAME_NODES,
    TABLE_NAME_PROGRAMMING_LANGUAGES,
    TABLE_NAME_PROGRAMMING_LANGUAGE_PRINCIPAL,
    TABLE_NAME_ROUTINES,
    TABLE_NAME_ROUTINE_TYPES,
    TABLE_NAME_TABLES,
} from './db-schema';

///
/// Table Creation
///
const CREATE_TABLE_TABLES = `
CREATE TABLE IF NOT EXISTS "${TABLE_NAME_TABLES}" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT),
	UNIQUE("name")
);
`;
const CREATE_TABLE_AUTO_COMPLETES = `
CREATE TABLE IF NOT EXISTS "${TABLE_NAME_AUTO_COMPLETES}" (
	"id"	INTEGER,
	"name"	TEXT,
	"icon"	INTEGER NOT NULL,
	"rule"	INTEGER NOT NULL,
	"insertion"	TEXT,
	"documentation"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
`;
const CREATE_TABLE_PROGRAMMING_LANGUAGES = `
CREATE TABLE IF NOT EXISTS "${TABLE_NAME_PROGRAMMING_LANGUAGES}" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
`;
const CREATE_TABLE_PROGRAMMING_LANGUAGE_PRINCIPAL = `
CREATE TABLE IF NOT EXISTS "${TABLE_NAME_PROGRAMMING_LANGUAGE_PRINCIPAL}" (
	"id"	INTEGER,
	"principal"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("principal") REFERENCES "${TABLE_NAME_PROGRAMMING_LANGUAGES}"
);
`;
const CREATE_TABLE_ROUTINE_TYPES = `
CREATE TABLE IF NOT EXISTS "${TABLE_NAME_ROUTINE_TYPES}" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
`;
const CREATE_TABLE_ROUTINES = `
CREATE TABLE IF NOT EXISTS "${TABLE_NAME_ROUTINES}" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL,
	"code"	TEXT,
	"type"	INTEGER NOT NULL,
	"notes"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("type") REFERENCES "${TABLE_NAME_ROUTINE_TYPES}"
);
`;
const CREATE_TABLE_LOCALES = `
CREATE TABLE IF NOT EXISTS "${TABLE_NAME_LOCALES}" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL UNIQUE,
	"isSystemCreated"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
`;
const CREATE_TABLE_LOCALE_PRINCIPAL = `
CREATE TABLE IF NOT EXISTS "${TABLE_NAME_LOCALE_PRINCIPAL}" (
	"id"	INTEGER,
	"principal"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("principal") REFERENCES "${TABLE_NAME_LOCALES}"
);
`;
const CREATE_TABLE_LOCALIZATION_TABLES = `
CREATE TABLE IF NOT EXISTS "${TABLE_NAME_LOCALIZATION_TABLES}" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL UNIQUE,
	"isSystemCreated"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
`;
const DEFAULT_LOCALE_ID = 0;
const CREATE_TABLE_LOCALIZATIONS = `
CREATE TABLE IF NOT EXISTS "${TABLE_NAME_LOCALIZATIONS}" (
	"id"	INTEGER,
	"name"	TEXT,
	"parent"	INTEGER NOT NULL,
	"isSystemCreated"	INTEGER NOT NULL,
	"${localeIdToColumn(DEFAULT_LOCALE_ID)}"	TEXT,
	FOREIGN KEY("parent") REFERENCES "${TABLE_NAME_LOCALIZATION_TABLES}",
	PRIMARY KEY("id" AUTOINCREMENT)
);
`;
const CREATE_TABLE_ACTORS = `
CREATE TABLE IF NOT EXISTS "${TABLE_NAME_ACTORS}" (
    "id"	INTEGER,
    "name"	TEXT NOT NULL,
    "color"	TEXT NOT NULL,
    "localizedName"	INTEGER,
	"isSystemCreated"	INTEGER NOT NULL,
    FOREIGN KEY("localizedName") REFERENCES "${TABLE_NAME_LOCALIZATIONS}",
    PRIMARY KEY("id" AUTOINCREMENT)
);
`;
const CREATE_TABLE_ACTOR_PRINCIPAL = `
CREATE TABLE IF NOT EXISTS "${TABLE_NAME_ACTOR_PRINCIPAL}" (
    "id"	INTEGER,
    "principal"	INTEGER,
    FOREIGN KEY("principal") REFERENCES "${TABLE_NAME_ACTORS}",
    PRIMARY KEY("id" AUTOINCREMENT)
);
`;
const CREATE_TABLE_CONVERSATIONS = `
CREATE TABLE IF NOT EXISTS "${TABLE_NAME_CONVERSATIONS}" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL,
	"parent"	INTEGER,
	"isFolder"	INTEGER NOT NULL,
	"notes"	TEXT,
	FOREIGN KEY("parent") REFERENCES "conversations",
	PRIMARY KEY("id" AUTOINCREMENT),
    UNIQUE("name","parent")
);
`;
const CREATE_TABLE_NODES = `
CREATE TABLE IF NOT EXISTS "${TABLE_NAME_NODES}" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL UNIQUE,
	"parent"	INTEGER NOT NULL,
	"actor"	INTEGER NOT NULL,
	"uiText"	INTEGER NOT NULL,
	"voiceText"	INTEGER NOT NULL,
	"condition"	INTEGER NOT NULL,
	"code"	INTEGER NOT NULL,
	"notes"	TEXT,
	FOREIGN KEY("uiText") REFERENCES "${TABLE_NAME_LOCALIZATIONS}",
	FOREIGN KEY("actor") REFERENCES "${TABLE_NAME_ACTORS}",
	FOREIGN KEY("voiceText") REFERENCES "${TABLE_NAME_LOCALIZATIONS}",
	FOREIGN KEY("parent") REFERENCES "${TABLE_NAME_CONVERSATIONS}",
	FOREIGN KEY("condition") REFERENCES "${TABLE_NAME_ROUTINES}",
	FOREIGN KEY("code") REFERENCES "${TABLE_NAME_ROUTINES}",
	PRIMARY KEY("id" AUTOINCREMENT)
);
`;
// TODO
// const CREATE_TABLE_PROPERTY_TYPES = `
// CREATE TABLE IF NOT EXISTS "${TABLE_NAME_PROPERTY_TYPES}" (
// 	"id"	INTEGER,
// 	"name"	TEXT NOT NULL UNIQUE,
// 	PRIMARY KEY("id" AUTOINCREMENT)
// );
// `;
// const CREATE_TABLE_PROPERTIES = `
// CREATE TABLE IF NOT EXISTS "${TABLE_NAME_PROPERTIES}" (
// 	"id"	INTEGER,
// 	"name"	TEXT NOT NULL,
// 	"defaultId"	INTEGER,
// 	"${PROPERTY_FK_COLUMN_NAME_ACTORS}"	INTEGER,
// 	"${PROPERTY_FK_COLUMN_NAME_CONVERSATIONS}"	INTEGER,
// 	"${PROPERTY_FK_COLUMN_NAME_NODES}"	INTEGER,
// 	"parentType"	INTEGER NOT NULL,
// 	"type"	INTEGER NOT NULL,
// 	"isDefault"	INTEGER NOT NULL,
// 	"bool"	INTEGER DEFAULT 0,
// 	"decimal"	NUMERIC DEFAULT 0,
// 	"integer"	INTEGER DEFAULT 0,
// 	"text"	TEXT,
// 	"localizedText"	INTEGER,
// 	FOREIGN KEY("defaultId") REFERENCES "${TABLE_NAME_DEFAULT_PROPERTIES}",
// 	FOREIGN KEY("parentActor") REFERENCES "${TABLE_NAME_ACTORS}",
// 	FOREIGN KEY("parentConversation") REFERENCES "${TABLE_NAME_CONVERSATIONS}",
// 	FOREIGN KEY("parentNode") REFERENCES "${TABLE_NAME_NODES}",
// 	FOREIGN KEY("parentType") REFERENCES "${TABLE_NAME_TABLES}",
// 	FOREIGN KEY("type") REFERENCES "${TABLE_NAME_PROPERTY_TYPES}",
// 	FOREIGN KEY("localizedText") REFERENCES "${TABLE_NAME_LOCALIZATIONS}",
// 	PRIMARY KEY("id" AUTOINCREMENT)
// );
// `;
// const CREATE_TABLE_DEFAULT_PROPERTIES = `
// CREATE TABLE IF NOT EXISTS "${TABLE_NAME_DEFAULT_PROPERTIES}" (
// 	"id"	INTEGER,
// 	"name"	TEXT NOT NULL,
// 	"type"	INTEGER NOT NULL,
// 	"parentType"	INTEGER NOT NULL,
// 	PRIMARY KEY("id" AUTOINCREMENT),
// 	FOREIGN KEY("type") REFERENCES "${TABLE_NAME_PROPERTY_TYPES}",
// 	FOREIGN KEY("parentType") REFERENCES "${TABLE_NAME_TABLES}"
// );`;
export const CREATE_TABLE_QUERIES = [
    CREATE_TABLE_TABLES,
    CREATE_TABLE_AUTO_COMPLETES,
    CREATE_TABLE_PROGRAMMING_LANGUAGES,
    CREATE_TABLE_PROGRAMMING_LANGUAGE_PRINCIPAL,
    CREATE_TABLE_ROUTINE_TYPES,
    CREATE_TABLE_ROUTINES,
    CREATE_TABLE_LOCALES,
    CREATE_TABLE_LOCALE_PRINCIPAL,
    CREATE_TABLE_LOCALIZATION_TABLES,
    CREATE_TABLE_LOCALIZATIONS,
    CREATE_TABLE_ACTORS,
    CREATE_TABLE_ACTOR_PRINCIPAL,
    CREATE_TABLE_CONVERSATIONS,
    CREATE_TABLE_NODES,
    // CREATE_TABLE_PROPERTY_TYPES,
    // CREATE_TABLE_PROPERTIES,
    // CREATE_TABLE_DEFAULT_PROPERTIES,
];

///
/// Table Initialization
///
let rowIndex: number;
// Tables
rowIndex = 0;
const INITIALIZE_TABLES = `
BEGIN TRANSACTION;
${DATABASE_TABLE_NAMES.map(
    (tableName: string) =>
        `INSERT OR IGNORE INTO ${TABLE_NAME_TABLES} (id, name) VALUES (${rowIndex++}, '${tableName}');`,
).join('\n')}
COMMIT;
`;
// Auto-Completes
// Programming Languages
rowIndex = 0;
const DEFAULT_PROGRAMMING_LANGUAGE_ID = rowIndex;
const INITIALIZE_PROGRAMMING_LANGUAGES = `
BEGIN TRANSACTION;
${PROGRAMMING_LANGUAGE_NAMES.map(
    (languageName: string) =>
        `INSERT OR IGNORE INTO ${TABLE_NAME_PROGRAMMING_LANGUAGES} (id, name) VALUES (${rowIndex++}, '${languageName}');`,
).join('\n')}
COMMIT;
`;
// Programming Language Principal
rowIndex = 0;
const INITIALIZE_PROGRAMMING_LANGUAGE_PRINCIPAL = `
INSERT OR IGNORE INTO ${TABLE_NAME_PROGRAMMING_LANGUAGE_PRINCIPAL} (id, principal) VALUES (${rowIndex++}, ${DEFAULT_PROGRAMMING_LANGUAGE_ID});`;
// Routine Types
rowIndex = 0;
const INITIALIZE_ROUTINE_TYPES = `
BEGIN TRANSACTION;
${ROUTINE_TYPES.map(
    (routineType) =>
        `INSERT OR IGNORE INTO ${TABLE_NAME_ROUTINE_TYPES} (id, name) VALUES (${routineType.id}, '${routineType.name}');`,
).join('\n')}
COMMIT;
`;
// Routines
rowIndex = 0;
const INITIALIZE_ROUTINES = `
BEGIN TRANSACTION;
INSERT OR IGNORE INTO ${TABLE_NAME_ROUTINES} (id, name, code, type) VALUES (${rowIndex++}, 'Do Nothing', '', ${ROUTINE_TYPE_ID_DEFAULT});
INSERT OR IGNORE INTO ${TABLE_NAME_ROUTINES} (id, name, code, type) VALUES (${rowIndex++}, 'Import Statements', '', ${ROUTINE_TYPE_ID_IMPORTS});
COMMIT;
`;
// Locales
rowIndex = DEFAULT_LOCALE_ID;
const INITIALIZE_LOCALES = `
INSERT OR IGNORE INTO ${TABLE_NAME_LOCALES} (id, name, isSystemCreated) VALUES (${rowIndex++}, 'en_US', true);`;
// Locale Principal
rowIndex = 0;
const INITIALIZE_LOCALE_PRINCIPAL = `
INSERT OR IGNORE INTO ${TABLE_NAME_LOCALE_PRINCIPAL} (id, principal) VALUES (${rowIndex++}, ${DEFAULT_LOCALE_ID});`;
// Localization Tables
rowIndex = 0;
const DEFAULT_LOCALIZATION_TABLE_ID = rowIndex;
const INITIALIZE_LOCALIZATION_TABLES = `
INSERT OR IGNORE INTO ${TABLE_NAME_LOCALIZATION_TABLES} (id, name, isSystemCreated) VALUES (${rowIndex++}, '${ACTOR_LOCALIZATION_TABLE_NAME}', true);`;
// Localizations
rowIndex = 0;
const DEFAULT_LOCALIZATION_ID = rowIndex;
const INITIALIZE_LOCALIZATIONS = `
INSERT OR IGNORE INTO ${TABLE_NAME_LOCALIZATIONS} (id, parent, isSystemCreated, '${localeIdToColumn(
    DEFAULT_LOCALE_ID,
)}') VALUES (${rowIndex++}, ${DEFAULT_LOCALIZATION_TABLE_ID}, true, 'Player');
`;
// Actors
rowIndex = 0;
const DEFAULT_ACTOR_ID = rowIndex;
const INITIALIZE_ACTORS = `
INSERT OR IGNORE INTO ${TABLE_NAME_ACTORS} (id, name, color, localizedName, isSystemCreated) VALUES (${rowIndex++}, 'Player', '${ACTORS_DEFAULT_COLOR}', ${DEFAULT_LOCALIZATION_ID}, true);`;
// Actor Principal
rowIndex = 0;
const INITIALIZE_ACTOR_PRINCIPAL = `
INSERT OR IGNORE INTO ${TABLE_NAME_ACTOR_PRINCIPAL} (id, principal) VALUES (${rowIndex++}, ${DEFAULT_ACTOR_ID});`;
// Conversations
// Nodes
// Property Types
// const INITIALIZE_PROPERTY_TYPES = `
// BEGIN TRANSACTION;
// ${PROPERTY_TYPES.map(
//     (propertyType) =>
//         `INSERT OR IGNORE INTO ${TABLE_NAME_PROPERTY_TYPES} (id, name) VALUES (${propertyType.id}, '${propertyType.name}');`,
// ).join('\n')}
// COMMIT;
// `;
export const INITIALIZE_TABLE_QUERIES = [
    INITIALIZE_TABLES,
    INITIALIZE_PROGRAMMING_LANGUAGES,
    INITIALIZE_PROGRAMMING_LANGUAGE_PRINCIPAL,
    INITIALIZE_ROUTINE_TYPES,
    INITIALIZE_ROUTINES,
    INITIALIZE_LOCALES,
    INITIALIZE_LOCALE_PRINCIPAL,
    INITIALIZE_LOCALIZATION_TABLES,
    INITIALIZE_LOCALIZATIONS,
    INITIALIZE_ACTORS,
    INITIALIZE_ACTOR_PRINCIPAL,
    // INITIALIZE_PROPERTY_TYPES,
];
