# Auto-generated by GameScript
# Conversation ID: 3
extends RefCounted

func cond_8(ctx: RunnerContext) -> bool:
	# TODO: Implement condition
	return true

func act_8(ctx: RunnerContext) -> void:
	# TODO: Implement action
	pass




