<script lang="ts">
    import { Tile } from 'carbon-components-svelte';
    import RoutineEditor from '../common/RoutineEditor.svelte';
    import { importRoutines } from '@lib/tables/routines-imports';
    import type { IDbRowView } from '@lib/api/db/db-view-row-interface';
    import type { Routine } from '@lib/api/db/db-schema';
    import { onDestroy } from 'svelte';

    let rowView: IDbRowView<Routine>;

    onDestroy(
        importRoutines.subscribe((rowViews: IDbRowView<Routine>[]) => {
            if (rowViews.length === 1) {
                rowView = rowViews[0];
            }
        }),
    );
</script>

<Tile>
    <h4>Imports</h4>
    <p>
        The import statements you add here will appear at the top of any code generated by
        GameScript thereby allowing you to reference code in your game from routines you write in
        the conversation editor.
    </p>
    <RoutineEditor {rowView} columnName={'code'} />
</Tile>
