using System;
using System.IO;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

namespace GameScript
{
    [CustomEditor(typeof(Settings))]
    class SettingsEditor : Editor
    {
        #region Variables
        [SerializeField]
        private VisualTreeAsset m_SettingsXML;
        #endregion

        public override VisualElement CreateInspectorGUI()
        {
            // Create custom inspector
            VisualElement root = new VisualElement();

            #region Runtime Settings
            // Max Conversations
            IntegerField maxConversations = new();
            maxConversations.name = "InitialConversationPool";
            maxConversations.label = "Initial Conversation Pool Size";
            maxConversations.tooltip =
                "This will decide how many simultaneous conversations can "
                + $"be run before {RuntimeConstants.k_AppName} needs to allocate more memory.";
            maxConversations.bindingPath = "InitialConversationPool";

            // Prevent Single Node Decisions
            Toggle preventSingleNodeChoices = new();
            preventSingleNodeChoices.name = "PreventSingleNodeChoices";
            preventSingleNodeChoices.label = "Prevent Single Node Choices";
            preventSingleNodeChoices.tooltip =
                "Normally, when a single node has UI Response Text set, it is treated as a "
                + "choice, even if it has no 'siblings'. This will prevent that behavior.";
            preventSingleNodeChoices.bindingPath = "PreventSingleNodeChoices";
            #endregion

            #region Runtime Settings Foldout
            // Runtime Settings Foldout
            Foldout runtimeSettingsFoldout = new();
            runtimeSettingsFoldout.name = "RuntimeSettings";
            runtimeSettingsFoldout.text = "Runtime Settings";
            runtimeSettingsFoldout.Add(maxConversations);
            runtimeSettingsFoldout.Add(preventSingleNodeChoices);
            #endregion

            #region GameScript
            // Generated Header
            Label generatedHeader = new();
            generatedHeader.name = "GeneratedHeader";
            generatedHeader.text = "Generated";

            // Generated Output Path (shows absolute, stores relative)
            TextField generatedPathField = new();
            generatedPathField.name = "GeneratedPath";
            generatedPathField.label = "Code & References Output Folder";
            generatedPathField.SetEnabled(false);

            // Select Generated Path Button (callback wired up after all elements declared)
            Button generatedButton = new();
            generatedButton.name = $"{RuntimeConstants.k_AppName}PathButton";
            generatedButton.text = $"Select Folder";
            generatedButton.tooltip =
                "Select a folder within the Assets folder to place files generated by "
                + $"{RuntimeConstants.k_AppName}.";
            #endregion

            #region Runtime Database
            // Runtime Database Header
            Label runtimeDatabaseHeader = new();
            runtimeDatabaseHeader.name = "RuntimeDatabaseHeader";
            runtimeDatabaseHeader.text = "Runtime Database";

            // Runtime Database Path (shows absolute, stores relative)
            TextField runtimeDatabasePath = new();
            runtimeDatabasePath.name = "RuntimeDatabaseDataPath";
            runtimeDatabasePath.label = "Streaming Assets Sub-Folder";
            runtimeDatabasePath.tooltip = "This is where the runtime game data will be stored.";
            runtimeDatabasePath.SetEnabled(false);

            // Runtime Database Path Button (callback wired up after all elements declared)
            Button conversationDataButton = new();
            conversationDataButton.name = "RuntimeDatabaseButton";
            conversationDataButton.text = "Select Folder";
            conversationDataButton.tooltip =
                "Select a folder within the StreamingAssets folder to place files exported by "
                + $"{RuntimeConstants.k_AppName} for use at runtime.";
            #endregion

            #region Editor Database
            // Editor Database Header
            Label databaseHeader = new();
            databaseHeader.name = "DatabaseHeader";
            databaseHeader.text = "Editor Database";

            // Editor Database Version
            TextField databaseVersionField = new();
            databaseVersionField.name = "DatabaseVersion";
            databaseVersionField.label = "Version";
            databaseVersionField.bindingPath = "DatabaseVersion";
            databaseVersionField.SetEnabled(false);
            databaseVersionField.RegisterValueChangedCallback(
                (ChangeEvent<string> change) =>
                {
                    OnDbVersionChanged(databaseVersionField, change.newValue);
                }
            );

            // Editor Database Path (shows absolute, stores relative)
            TextField databasePathField = new();
            databasePathField.name = "DatabasePath";
            databasePathField.label = "Database";
            databasePathField.SetEnabled(false);

            // Select Editor Database Button
            Button databaseSelectButton = new();
            databaseSelectButton.name = "SelectDatabase";
            databaseSelectButton.text = "Select Database";
            databaseSelectButton.tooltip =
                "Select a database file to use for importing conversation data.";

            // Import Database Button
            Button databaseImportButton = new();
            databaseImportButton.name = "ImportDatabase";
            databaseImportButton.text = "Import Database";
            databaseImportButton.tooltip =
                "Import the selected database. This will prepare "
                + "all of your conversation data for runtime use and may take some time.";

            // Wire up Select Database Button callback
            databaseSelectButton.clickable.clicked += () =>
            {
                string absoluteDbPath = EditorUtility.OpenFilePanel("Select Database", "", "");
                if (string.IsNullOrEmpty(absoluteDbPath))
                    return;

                // Convert to relative and save
                string relativeDbPath = GetRelativePathFromProjectRoot(absoluteDbPath);
                serializedObject.FindProperty("DatabasePath").stringValue = relativeDbPath;
                serializedObject.ApplyModifiedProperties();

                // Update display with absolute path
                databasePathField.value = absoluteDbPath;

                // Revalidate to update Import button state
                Settings s = (Settings)serializedObject.targetObject;
                OnDbPathChanged(databaseVersionField, absoluteDbPath);
                ValidatePathsAndUpdateImportButton(
                    generatedPathField,
                    runtimeDatabasePath,
                    databasePathField,
                    databaseImportButton,
                    s
                );
            };

            // Wire up Import Database Button callback
            databaseImportButton.clickable.clicked += () =>
            {
                // Make sure import isn't in progress
                if (DatabaseImporter.IsImporting)
                {
                    EditorUtility.DisplayDialog(
                        "Import in Progress",
                        "Database import is in progress. Please wait for it to finish.",
                        "OK"
                    );
                    return;
                }

                // Load database using absolute paths
                Settings settings = (Settings)serializedObject.targetObject;
                string absoluteDbPath = settings.GetAbsoluteDatabasePath();
                string gameScriptOutputPath = settings.GetAbsoluteGeneratedPath();
                string conversationOutputPath = settings.GetAbsoluteGameDataPath();
                DatabaseImporter.ImportDatabase(
                    absoluteDbPath,
                    gameScriptOutputPath,
                    conversationOutputPath
                );
            };

            // Wire up Runtime Database Path Button callback
            conversationDataButton.clickable.clicked += () =>
            {
                string streamingAssetsPath = Application.streamingAssetsPath;
                if (!Directory.Exists(streamingAssetsPath))
                {
                    Directory.CreateDirectory(streamingAssetsPath);
                }
                string absolutePath = EditorUtility.OpenFolderPanel(
                    "Select Streaming Assets Sub-Folder",
                    streamingAssetsPath,
                    RuntimeConstants.k_AppName
                );
                if (!string.IsNullOrEmpty(absolutePath))
                {
                    // Convert to relative and save
                    string relativePath = GetRelativePathFromStreamingAssets(absolutePath);
                    if (relativePath == null)
                    {
                        EditorUtility.DisplayDialog(
                            "Invalid Path",
                            "The selected folder must be within the StreamingAssets folder.",
                            "OK"
                        );
                        return;
                    }
                    serializedObject.FindProperty("GameDataPath").stringValue = relativePath;
                    serializedObject.ApplyModifiedProperties();

                    // Update display with absolute path
                    runtimeDatabasePath.value = absolutePath;

                    // Revalidate to update Import button state
                    Settings s = (Settings)serializedObject.targetObject;
                    ValidatePathsAndUpdateImportButton(
                        generatedPathField,
                        runtimeDatabasePath,
                        databasePathField,
                        databaseImportButton,
                        s
                    );
                }
            };

            // Wire up Generated Path Button callback
            generatedButton.clickable.clicked += () =>
            {
                string absolutePath = EditorUtility.OpenFolderPanel(
                    $"Select {RuntimeConstants.k_AppName} Folder",
                    Application.dataPath,
                    ""
                );
                if (!string.IsNullOrEmpty(absolutePath))
                {
                    // Convert to relative and save
                    string relativePath = GetRelativePathFromAssets(absolutePath);
                    if (relativePath == null)
                    {
                        EditorUtility.DisplayDialog(
                            "Invalid Path",
                            "The selected folder must be within the Assets folder.",
                            "OK"
                        );
                        return;
                    }
                    serializedObject.FindProperty("GeneratedPath").stringValue = relativePath;
                    serializedObject.ApplyModifiedProperties();

                    // Update display with absolute path
                    generatedPathField.value = absolutePath;

                    // Revalidate to update Import button state
                    Settings s = (Settings)serializedObject.targetObject;
                    ValidatePathsAndUpdateImportButton(
                        generatedPathField,
                        runtimeDatabasePath,
                        databasePathField,
                        databaseImportButton,
                        s
                    );
                }
            };
            #endregion

            #region Editor Settings Foldout
            Foldout editorSettingsFoldout = new();
            editorSettingsFoldout.name = "EditorSettings";
            editorSettingsFoldout.text = "Editor Settings";
            editorSettingsFoldout.Add(generatedHeader);
            editorSettingsFoldout.Add(generatedPathField);
            editorSettingsFoldout.Add(generatedButton);

            editorSettingsFoldout.Add(runtimeDatabaseHeader);
            editorSettingsFoldout.Add(runtimeDatabasePath);
            editorSettingsFoldout.Add(conversationDataButton);

            editorSettingsFoldout.Add(databaseHeader);
            editorSettingsFoldout.Add(databasePathField);
            editorSettingsFoldout.Add(databaseVersionField);
            editorSettingsFoldout.Add(databaseSelectButton);
            editorSettingsFoldout.Add(databaseImportButton);
            #endregion

            #region Initialization
            // Get settings for initial validation
            Settings settings = (Settings)serializedObject.targetObject;

            // Initialize path displays with absolute paths
            generatedPathField.value = settings.GetAbsoluteGeneratedPath();
            runtimeDatabasePath.value = settings.GetAbsoluteGameDataPath();
            databasePathField.value = settings.GetAbsoluteDatabasePath();

            // Initialize database version display
            OnDbPathChanged(databaseVersionField, settings.GetAbsoluteDatabasePath());

            // Validate paths and set initial Import button state
            ValidatePathsAndUpdateImportButton(
                generatedPathField,
                runtimeDatabasePath,
                databasePathField,
                databaseImportButton,
                settings
            );
            #endregion

            #region Default Inspector
            // Default Inspector Foldout
            // Foldout defaultInspectorFoldout = new Foldout();
            // defaultInspectorFoldout.name = "DefaultInspector";
            // defaultInspectorFoldout.text = "Default Inspector";
            // InspectorElement.FillDefaultInspector(defaultInspectorFoldout, serializedObject, this);
            #endregion

            // Add All Elements
            root.Add(runtimeSettingsFoldout);
            root.Add(editorSettingsFoldout);
            // root.Add(defaultInspectorFoldout); // Used during developement
            return root;
        }

        #region Event Handlers
        private void OnDbPathChanged(TextField databaseVersionField, string newPath)
        {
            // Update version field based on database path
            if (File.Exists(newPath))
            {
                databaseVersionField.value = DatabaseImporter.GetDatabaseVersion(newPath);
            }
            else
            {
                databaseVersionField.value = "";
            }
        }

        private void OnDbVersionChanged(TextField databaseVersionField, string newVersion)
        {
            // Highlight version field if it doesn't match current version
            if (newVersion == RuntimeConstants.k_Version || string.IsNullOrEmpty(newVersion))
            {
                UnsetElementWarning(databaseVersionField);
            }
            else
            {
                SetElementWarning(databaseVersionField);
            }
        }

        /// <summary>
        /// Validates all required paths and updates the Import button state and field highlighting
        /// </summary>
        private void ValidatePathsAndUpdateImportButton(
            TextField generatedPathField,
            TextField runtimeDatabasePath,
            TextField databasePathField,
            Button databaseImportButton,
            Settings settings
        )
        {
            // Get absolute paths for validation
            string absoluteGeneratedPath = settings.GetAbsoluteGeneratedPath();
            string absoluteGameDataPath = settings.GetAbsoluteGameDataPath();
            string absoluteDatabasePath = settings.GetAbsoluteDatabasePath();

            // Generated path must exist (needed for writing generated code)
            bool generatedPathValid = IsPathValid(
                absoluteGeneratedPath,
                Application.dataPath,
                requireExists: true
            );

            // Game data path can be created by importer, so doesn't need to exist yet
            bool gameDataPathValid = IsPathValid(
                absoluteGameDataPath,
                Application.streamingAssetsPath,
                requireExists: false
            );

            // Database file must exist
            bool databasePathValid = !string.IsNullOrEmpty(absoluteDatabasePath)
                && File.Exists(absoluteDatabasePath);

            // Update field highlighting
            if (generatedPathValid)
            {
                UnsetElementWarning(generatedPathField);
            }
            else
            {
                SetElementWarning(generatedPathField);
            }

            if (gameDataPathValid)
            {
                UnsetElementWarning(runtimeDatabasePath);
            }
            else
            {
                SetElementWarning(runtimeDatabasePath);
            }

            if (databasePathValid)
            {
                UnsetElementWarning(databasePathField);
            }
            else
            {
                SetElementWarning(databasePathField);
            }

            // Enable Import button only if all paths are valid
            bool allPathsValid = generatedPathValid && gameDataPathValid && databasePathValid;
            databaseImportButton.SetEnabled(allPathsValid);

            // Make Import button green when enabled
            if (allPathsValid)
            {
                databaseImportButton.style.backgroundColor = new(new Color(0.2f, 0.6f, 0.2f));
            }
            else
            {
                databaseImportButton.style.backgroundColor = new(Color.clear);
            }
        }

        /// <summary>
        /// Checks if a path is valid and optionally exists within the required parent folder
        /// </summary>
        private bool IsPathValid(string path, string requiredParent, bool requireExists)
        {
            if (string.IsNullOrEmpty(path))
                return false;

            // Check if it exists (if required)
            if (requireExists && !IsValidFolder(path))
                return false;

            // For non-existing paths, check if it's a valid path format and within parent
            if (!requireExists)
            {
                try
                {
                    // Validate it's a proper path format
                    Path.GetFullPath(path);

                    // Check if it would be within the required parent
                    string normalizedPath = Path.GetFullPath(path).Replace('\\', '/');
                    string normalizedParent = Path.GetFullPath(requiredParent).Replace('\\', '/');

                    if (!normalizedPath.StartsWith(normalizedParent, StringComparison.OrdinalIgnoreCase))
                        return false;
                }
                catch (Exception)
                {
                    return false;
                }
            }
            else
            {
                // For existing paths, use the stricter subfolder check
                if (!IsValidSubFolder(path, requiredParent))
                    return false;
            }

            return true;
        }
        #endregion

        #region Helpers
        private void UnsetElementWarning(BindableElement element)
        {
            element.style.color = new(Color.white);
            element.style.backgroundColor = new(Color.clear);
        }

        private void SetElementWarning(BindableElement element)
        {
            element.style.color = new(Color.black);
            element.style.backgroundColor = new(Color.red);
        }

        private bool IsValidFolder(string path)
        {
            try
            {
                Path.GetFullPath(path);
                return Directory.Exists(path);
            }
            catch (Exception)
            {
                return false;
            }
        }

        private bool IsValidSubFolder(string path, string parent)
        {
            DirectoryInfo dir = new DirectoryInfo(path);
            DirectoryInfo streamingAssets = new DirectoryInfo(parent);
            while (dir.Parent != null)
            {
                if (dir.Parent.FullName == streamingAssets.FullName)
                    return true;
                else
                    dir = dir.Parent;
            }
            return false;
        }

        /// <summary>
        /// Gets a relative path that must be within the specified parent folder.
        /// Returns null if the path is outside the parent folder.
        /// </summary>
        private string GetRelativeSubPath(string parentPath, string absolutePath)
        {
            if (string.IsNullOrEmpty(parentPath) || string.IsNullOrEmpty(absolutePath))
                return null;

            string relativePath = Path.GetRelativePath(parentPath, absolutePath).Replace('\\', '/');

            // If the relative path starts with "..", it's outside the parent folder
            if (relativePath.StartsWith(".."))
                return null;

            return relativePath;
        }

        private string GetRelativePathFromStreamingAssets(string absolutePath)
        {
            return GetRelativeSubPath(Application.streamingAssetsPath, absolutePath);
        }

        private string GetRelativePathFromAssets(string absolutePath)
        {
            return GetRelativeSubPath(Application.dataPath, absolutePath);
        }

        private string GetRelativePathFromProjectRoot(string absolutePath)
        {
            string projectRoot = Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
            return Path.GetRelativePath(projectRoot, absolutePath).Replace('\\', '/');
        }
        #endregion
    }
}
