# Auto-generated by GameScript
# Conversation ID: 1
extends RefCounted

func act_2(ctx: RunnerContext, token: CancellationToken) -> void:
	# TODO: Implement action
	pass

func cond_2(ctx: RunnerContext) -> bool:
	# TODO: Implement condition
	return true
